version: 2
jobs:
    python-unit:
        working_directory: ~/pyunit
        docker:
          - image: python:3.6.3
        steps:
          - checkout
          - run:
              name: install packages
              command: scripts/install.sh
          - run:
              name: flake8
              command: flake8
          - run:
              name: tests
              command: nosetests --with-coverage
          - run:
              name: upload coverage report
              command: codecov
    js-unit:
        working_directory: ~/jsunit
        docker:
          - image: circleci/node:latest-browsers
        steps:
          - checkout
          - run:
              name: install
              command: yarn install
          - run:
              name: test
              command: yarn test
    docker:
        working_directory: ~/docker
        machine: true
        steps:
            - run:
                name: build image
                command: make image
            - run:
                name: run tests
                command: make
            - run:
                name: Login to docker hub
                command: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            - run:
                name: push image
                command: make push

workflows:
  version: 2
  build-deploy:
    jobs:
      - python-unit
      - js-unit
      - docker:
          requires:
            - python-unit
            - js-unit
